version: '3.7'
services:
  redis:
    image: redis:5
    labels:
      - "author=rohaualexandr"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "6379:6379"
    command: redis-server --save "" --appendonly no